list: $/plus/weiphp/models/materialnews/columns.yaml
modelClass: Plus\Weiphp\Models\MaterialNews
title: MaterialNews
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'plus/weiphp/materialnews/update/:id'
