list: $/plus/weiphp/models/materialfile/columns.yaml
modelClass: Plus\Weiphp\Models\MaterialFile
title: MaterialVoice
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'plus/weiphp/materialvoice/update/:id'
