list: $/plus/weiphp/models/materialfile/columns2.yaml
modelClass: Plus\Weiphp\Models\MaterialFile
title: MaterialVideo
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'plus/weiphp/materialvideo/update/:id'
