title: MaterialImage
modelClass: Plus\Weiphp\Models\MaterialImage
list: $/plus/weiphp/models/materialimage/columns.yaml
recordUrl: 'plus/weiphp/materialimage/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
