list: $/plus/weiphp/models/materialtext/columns.yaml
modelClass: Plus\Weiphp\Models\MaterialText
title: MaterialText
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'plus/weiphp/materialtext/update/:id'
